-- Write an SQL script to automate the creation of the bookmarks table in the database
-- Seed the table with at least 10 rows of data

-- remove the table if it exists
drop table if exists bookmarks;

-- (re)create the table
create table bookmarks (
  id integer primary key generated by default as identity,
  title text not null,
  url text not null,
  description text,
  rating integer default 1
);

-- test data with all values
insert into bookmarks (title, url, description, rating)
values
  ('Thinkful', 'https://www.thinkful.com', 'Think outside the classroom', 5),
  ('Google', 'https://www.google.com', 'Where we find everything else', 4),
  ('MDN', 'https://developer.mozilla.org', 'The only place to find web documentation', 5),
  ('Reddit', 'https://www.reddit.com', 'The front page of the internet', 2),
  ('Stack Overflow', 'https://stackoverflow.com/', 'Get your questions answered!', 4),
  ('Smitten Kitchen', 'https://smittenkitchen.com/recipes/', 'Find something to eat', 5),
  ('The Atlantic', 'https://www.theatlantic.com/', 'Some mid-form journalism', 3);

-- test data missing rating
insert into bookmarks (title, url, description)
values
  ('Facebook', 'http://www.facebook.com', 'Kind of a waste of time');

-- test data missing description
insert into bookmarks (title, url, rating)
values
  ('YNAB', 'https://www.youneedabudget.com/', 4);

-- test data missing description & rating
insert into bookmarks (title, url)
values
  ('Slack', 'https://slack.com/');